name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build_job:

    runs-on: ubuntu-latest
    env:
      DOCKER_USER: ${{ secrets.DOCKER_USER }} 
      DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
      IMAGE_NAME: catalog-service
      IMAGE_VERSION: latest

    steps:
    - uses: actions/checkout@v4
    - name: Login to Docker Hub
      run:
        docker login -u $DOCKER_USER -p $DOCKER_PASSWORD
    - name: Build the Docker image
      run: docker build . -f CatalogServiceAPI/Dockerfile -t ${DOCKER_USER}/${IMAGE_NAME}:${IMAGE_VERSION}
    - name: Push Docker image to Docker Hub
      run: docker push ${DOCKER_USER}/${IMAGE_NAME}:${IMAGE_VERSION}


